import json
import sys
import os
from datetime import datetime
from dotenv import load_dotenv

# Add the current directory to sys.path so we can import utils
sys.path.append(os.getcwd())

from utils.db_utils import set_db_config
from utils.procurement_purchase_request import create_purchase_request

# Load environment variables
load_dotenv()

# Initialize DB config
set_db_config(
    os.getenv("DB_PATH"),
    os.getenv("DB_USER"),
    os.getenv("DB_PASSWORD"),
    os.getenv("DB_HOST")
)

payload = {
    "requesterId": "U001",
    "departmentId": "IT",
    "costCenter": "IT-OPS",
    "supplierId": "SUP-001",
    "currency": "MYR",
    "requestDate": "2026-04-21",
    "requiredDate": "2026-04-29",
    "justification": "Sample Draft PR",
    "deliveryLocation": "HQ Main Store",
    "notes": "Generated by script",
    "status": 0, # Changed 'DRAFT' to 0 for integer compatibility
    "totalAmount": 2180.0,
    "lineItems": [
        {
            "itemCode": "ITM-LAP-001",
            "itemName": "Business Laptop",
            "description": "14 inch business laptop",
            "quantity": 2,
            "unitPrice": 1000,
            "tax": 180,
            "amount": 2180,
        }
    ],
}

try:
    result = create_purchase_request(payload, "sqlsupport")
    print(json.dumps(result))
except Exception as e:
    import traceback
    traceback.print_exc()
    sys.exit(1)
