SET SQL DIALECT 3;

/*
PricingPriorityRule schema for Firebird.
BIT/GETDATE() from the original requirement are represented as SMALLINT and CURRENT_TIMESTAMP
for Firebird compatibility while preserving the same business behavior.
*/

CREATE TABLE PricingPriorityRule (
    PricingPriorityRuleId INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RuleCode VARCHAR(50) NOT NULL,
    RuleName VARCHAR(100) NOT NULL,
    PriorityNo INTEGER NOT NULL,
    IsEnabled SMALLINT DEFAULT 1 NOT NULL,
    AddDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EditDate TIMESTAMP,
    CONSTRAINT UQ_PricingPriorityRule_RuleCode UNIQUE (RuleCode),
    CONSTRAINT CK_PricingPriorityRule_IsEnabled CHECK (IsEnabled IN (0, 1))
);

CREATE ASC INDEX IDX_PricingPriorityRule_PriorityNo ON PricingPriorityRule (PriorityNo);

INSERT INTO PricingPriorityRule (RuleCode, RuleName, PriorityNo, IsEnabled)
VALUES ('CUSTOMER_PRICE_TAG', 'Customer Price Tag', 1, 1);
INSERT INTO PricingPriorityRule (RuleCode, RuleName, PriorityNo, IsEnabled)
VALUES ('REF_PRICE_BASED_ON_UOM', 'Ref. Price of Item Based on UOM', 2, 1);
INSERT INTO PricingPriorityRule (RuleCode, RuleName, PriorityNo, IsEnabled)
VALUES ('MIN_MAX_SELLING_PRICE', 'Min & Max Selling Price', 3, 1);
INSERT INTO PricingPriorityRule (RuleCode, RuleName, PriorityNo, IsEnabled)
VALUES ('LAST_QUOTATION_SELLING_PRICE', 'Last Quotation Selling Price', 4, 1);
INSERT INTO PricingPriorityRule (RuleCode, RuleName, PriorityNo, IsEnabled)
VALUES ('LAST_SALES_ORDER_SELLING_PRICE', 'Last Sales Order Selling Price', 5, 1);
INSERT INTO PricingPriorityRule (RuleCode, RuleName, PriorityNo, IsEnabled)
VALUES ('LAST_SALES_DELIVERY_ORDER_SELLING_PRICE', 'Last Sales Delivery Order Selling Price', 6, 1);
INSERT INTO PricingPriorityRule (RuleCode, RuleName, PriorityNo, IsEnabled)
VALUES ('LAST_SALES_INVOICE_SELLING_PRICE', 'Last Sales Invoice Selling Price', 7, 1);
INSERT INTO PricingPriorityRule (RuleCode, RuleName, PriorityNo, IsEnabled)
VALUES ('LAST_CASH_SALES_SELLING_PRICE', 'Last Cash Sales Selling Price', 8, 1);
INSERT INTO PricingPriorityRule (RuleCode, RuleName, PriorityNo, IsEnabled)
VALUES ('LAST_SALES_INVOICE_CASH_SALES_SELLING_PRICE', 'Last Sales Invoice / Cash Sales Selling Price', 9, 1);

COMMIT;

/*
Safe update script pattern for reordered priorities.
Run inside a transaction and update every row together.
*/
UPDATE PricingPriorityRule
SET PriorityNo = 1,
    IsEnabled = 1,
    EditDate = CURRENT_TIMESTAMP
WHERE RuleCode = 'CUSTOMER_PRICE_TAG';

UPDATE PricingPriorityRule
SET PriorityNo = 2,
    IsEnabled = 1,
    EditDate = CURRENT_TIMESTAMP
WHERE RuleCode = 'REF_PRICE_BASED_ON_UOM';

UPDATE PricingPriorityRule
SET PriorityNo = 3,
    IsEnabled = 1,
    EditDate = CURRENT_TIMESTAMP
WHERE RuleCode = 'MIN_MAX_SELLING_PRICE';

UPDATE PricingPriorityRule
SET PriorityNo = 4,
    IsEnabled = 1,
    EditDate = CURRENT_TIMESTAMP
WHERE RuleCode = 'LAST_QUOTATION_SELLING_PRICE';

UPDATE PricingPriorityRule
SET PriorityNo = 5,
    IsEnabled = 1,
    EditDate = CURRENT_TIMESTAMP
WHERE RuleCode = 'LAST_SALES_ORDER_SELLING_PRICE';

UPDATE PricingPriorityRule
SET PriorityNo = 6,
    IsEnabled = 1,
    EditDate = CURRENT_TIMESTAMP
WHERE RuleCode = 'LAST_SALES_DELIVERY_ORDER_SELLING_PRICE';

UPDATE PricingPriorityRule
SET PriorityNo = 7,
    IsEnabled = 1,
    EditDate = CURRENT_TIMESTAMP
WHERE RuleCode = 'LAST_SALES_INVOICE_SELLING_PRICE';

UPDATE PricingPriorityRule
SET PriorityNo = 8,
    IsEnabled = 1,
    EditDate = CURRENT_TIMESTAMP
WHERE RuleCode = 'LAST_CASH_SALES_SELLING_PRICE';

UPDATE PricingPriorityRule
SET PriorityNo = 9,
    IsEnabled = 1,
    EditDate = CURRENT_TIMESTAMP
WHERE RuleCode = 'LAST_SALES_INVOICE_CASH_SALES_SELLING_PRICE';

COMMIT;
